import type { PantryItem } from "./types"

export const PANTRY: PantryItem[] = [
  { name: "Chicken Breast (raw)", grams: 1000, category: "Protein" },
  { name: "Salmon Fillet", grams: 600, category: "Protein" },
  { name: "Lean Beef Mince (5% fat)", grams: 800, category: "Protein" },
  { name: "Egg (whole)", grams: 600, category: "Protein" },
  { name: "White Rice (cooked)", grams: 1200, category: "Grain" },
  { name: "Rolled Oats", grams: 800, category: "Grain" },
  { name: "Greek Yogurt (0% fat)", grams: 1000, category: "Dairy" },
  { name: "Broccoli", grams: 700, category: "Veg" },
  { name: "Sweet Potato", grams: 1000, category: "Veg" },
  { name: "Spinach", grams: 400, category: "Veg" },
  { name: "Almonds", grams: 300, category: "Fat" },
  { name: "Olive Oil", grams: 500, category: "Fat" },
  { name: "Whey Protein Powder", grams: 1000, category: "Protein" },
  { name: "Quinoa (cooked)", grams: 800, category: "Grain" },
  { name: "Chickpeas (cooked)", grams: 600, category: "Grain" },
  { name: "Banana", grams: 600, category: "Fruit" },
  { name: "Blueberries", grams: 300, category: "Fruit" },
  { name: "Tofu (firm)", grams: 500, category: "Protein" },
  { name: "Cottage Cheese", grams: 500, category: "Dairy" },
  { name: "Honey", grams: 250, category: "Fruit" },
  { name: "Cod Fillet", grams: 500, category: "Protein" },
  { name: "Tuna (canned)", grams: 480, category: "Protein" },
  { name: "Turkey Breast Mince", grams: 700, category: "Protein" },
  { name: "Shrimp", grams: 400, category: "Protein" },
  { name: "Egg White", grams: 500, category: "Protein" },
  { name: "Lentils (cooked)", grams: 600, category: "Grain" },
  { name: "Black Beans (cooked)", grams: 500, category: "Grain" },
  { name: "Brown Rice (cooked)", grams: 900, category: "Grain" },
  { name: "Whole Wheat Pasta", grams: 700, category: "Grain" },
  { name: "Couscous", grams: 400, category: "Grain" },
  { name: "Asparagus", grams: 300, category: "Veg" },
  { name: "Kale", grams: 250, category: "Veg" },
  { name: "Brussels Sprouts", grams: 400, category: "Veg" },
  { name: "Cauliflower", grams: 600, category: "Veg" },
  { name: "Bell Pepper", grams: 450, category: "Veg" },
  { name: "Carrot", grams: 700, category: "Veg" },
  { name: "Cucumber", grams: 500, category: "Veg" },
  { name: "Cherry Tomatoes", grams: 400, category: "Veg" },
  { name: "Zucchini", grams: 350, category: "Veg" },
  { name: "Mushrooms", grams: 300, category: "Veg" },
  { name: "Red Onion", grams: 500, category: "Veg" },
  { name: "Garlic", grams: 120, category: "Veg" },
  { name: "Milk (skimmed)", grams: 1000, category: "Dairy" },
  { name: "Cheddar Cheese", grams: 250, category: "Dairy" },
  { name: "Feta Cheese", grams: 180, category: "Dairy" },
  { name: "Peanut Butter", grams: 350, category: "Fat" },
  { name: "Chia Seeds", grams: 200, category: "Fat" },
  { name: "Walnuts", grams: 150, category: "Fat" },
  { name: "Apple", grams: 600, category: "Fruit" },
  { name: "Strawberries", grams: 250, category: "Fruit" },
]

export const PANTRY_NAMES = new Set(PANTRY.map((p) => p.name))
