import type { Recipe } from "./types"

export const RECIPES: Recipe[] = [
  {
    id: 1,
    name: "Grilled Chicken & Rice Bowl",
    mealType: "Lunch",
    nutriScoreGrade: "B",
    totalGrams: 1015,
    calories: 842,
    protein: 89,
    carbs: 96,
    fat: 22,
    sugar: 3,
    ingredients: [
      { name: "Chicken Breast (raw)", grams: 500 },
      { name: "White Rice (cooked)", grams: 300 },
      { name: "Broccoli", grams: 200 },
      { name: "Olive Oil", grams: 15 },
    ],
  },
  {
    id: 2,
    name: "Beef & Sweet Potato Skillet",
    mealType: "Dinner",
    nutriScoreGrade: "C",
    totalGrams: 940,
    calories: 720,
    protein: 72,
    carbs: 64,
    fat: 24,
    sugar: 8,
    ingredients: [
      { name: "Lean Beef Mince (5% fat)", grams: 400 },
      { name: "Sweet Potato", grams: 350 },
      { name: "Spinach", grams: 150 },
      { name: "Olive Oil", grams: 15 },
    ],
  },
  {
    id: 3,
    name: "Salmon with Quinoa & Greens",
    mealType: "Dinner",
    nutriScoreGrade: "A",
    totalGrams: 880,
    calories: 612,
    protein: 62,
    carbs: 48,
    fat: 22,
    sugar: 2,
    ingredients: [
      { name: "Salmon Fillet", grams: 350 },
      { name: "Quinoa (cooked)", grams: 300 },
      { name: "Broccoli", grams: 150 },
      { name: "Spinach", grams: 80 },
    ],
  },
  {
    id: 4,
    name: "Protein Power Oats",
    mealType: "Breakfast",
    nutriScoreGrade: "A",
    totalGrams: 450,
    calories: 702,
    protein: 55,
    carbs: 78,
    fat: 16,
    sugar: 14,
    ingredients: [
      { name: "Rolled Oats", grams: 100 },
      { name: "Whey Protein Powder", grams: 40 },
      { name: "Banana", grams: 120 },
      { name: "Greek Yogurt (0% fat)", grams: 150 },
      { name: "Almonds", grams: 20 },
    ],
  },
  {
    id: 5,
    name: "Veggie Omelette",
    mealType: "Breakfast",
    nutriScoreGrade: "B",
    totalGrams: 420,
    calories: 388,
    protein: 32,
    carbs: 10,
    fat: 24,
    sugar: 4,
    ingredients: [
      { name: "Egg (whole)", grams: 200 },
      { name: "Spinach", grams: 80 },
      { name: "Broccoli", grams: 100 },
      { name: "Olive Oil", grams: 10 },
    ],
  },
  {
    id: 6,
    name: "Greek Yogurt, Almonds & Honey",
    mealType: "Snack",
    nutriScoreGrade: "B",
    totalGrams: 320,
    calories: 342,
    protein: 26,
    carbs: 34,
    fat: 12,
    sugar: 22,
    ingredients: [
      { name: "Greek Yogurt (0% fat)", grams: 250 },
      { name: "Almonds", grams: 30 },
      { name: "Honey", grams: 40 },
    ],
  },
  {
    id: 7,
    name: "Turkey Lettuce Wraps",
    mealType: "Lunch",
    nutriScoreGrade: "A",
    totalGrams: 560,
    calories: 412,
    protein: 48,
    carbs: 18,
    fat: 14,
    sugar: 5,
    ingredients: [
      { name: "Turkey Breast Mince", grams: 350 },
      { name: "Spinach", grams: 120 },
      { name: "Olive Oil", grams: 10 },
    ],
  },
  {
    id: 8,
    name: "Cod, Broccoli & Brown Rice",
    mealType: "Dinner",
    nutriScoreGrade: "A",
    totalGrams: 820,
    calories: 498,
    protein: 58,
    carbs: 52,
    fat: 8,
    sugar: 1,
    ingredients: [
      { name: "Cod Fillet", grams: 350 },
      { name: "White Rice (cooked)", grams: 300 },
      { name: "Broccoli", grams: 170 },
    ],
  },
  {
    id: 9,
    name: "Tuna & Chickpea Salad",
    mealType: "Lunch",
    nutriScoreGrade: "A",
    totalGrams: 600,
    calories: 468,
    protein: 52,
    carbs: 42,
    fat: 10,
    sugar: 4,
    ingredients: [
      { name: "Tuna (canned)", grams: 250 },
      { name: "Chickpeas (cooked)", grams: 250 },
      { name: "Spinach", grams: 90 },
      { name: "Olive Oil", grams: 10 },
    ],
  },
  {
    id: 10,
    name: "Chicken & Quinoa Power Bowl",
    mealType: "Lunch",
    nutriScoreGrade: "A",
    totalGrams: 850,
    calories: 678,
    protein: 71,
    carbs: 62,
    fat: 16,
    sugar: 3,
    ingredients: [
      { name: "Chicken Breast (raw)", grams: 400 },
      { name: "Quinoa (cooked)", grams: 300 },
      { name: "Broccoli", grams: 150 },
    ],
  },
  {
    id: 11,
    name: "Tofu & Vegetable Stir-Fry",
    mealType: "Dinner",
    nutriScoreGrade: "A",
    totalGrams: 720,
    calories: 380,
    protein: 44,
    carbs: 32,
    fat: 14,
    sugar: 4,
    ingredients: [
      { name: "Tofu (firm)", grams: 400 },
      { name: "Broccoli", grams: 200 },
      { name: "Spinach", grams: 110 },
      { name: "Olive Oil", grams: 10 },
    ],
  },
  {
    id: 12,
    name: "Lentil & Vegetable Soup",
    mealType: "Lunch",
    nutriScoreGrade: "A",
    totalGrams: 700,
    calories: 356,
    protein: 28,
    carbs: 54,
    fat: 6,
    sugar: 9,
    ingredients: [
      { name: "Lentils (cooked)", grams: 350 },
      { name: "Sweet Potato", grams: 200 },
      { name: "Spinach", grams: 150 },
    ],
  },
  {
    id: 13,
    name: "Egg White & Spinach Scramble",
    mealType: "Breakfast",
    nutriScoreGrade: "A",
    totalGrams: 380,
    calories: 246,
    protein: 34,
    carbs: 8,
    fat: 8,
    sugar: 3,
    ingredients: [
      { name: "Egg White", grams: 300 },
      { name: "Spinach", grams: 80 },
    ],
  },
  {
    id: 14,
    name: "Greek Yogurt, Berries & Chia",
    mealType: "Breakfast",
    nutriScoreGrade: "A",
    totalGrams: 420,
    calories: 318,
    protein: 28,
    carbs: 36,
    fat: 8,
    sugar: 18,
    ingredients: [
      { name: "Greek Yogurt (0% fat)", grams: 250 },
      { name: "Blueberries", grams: 120 },
      { name: "Chia Seeds", grams: 20 },
    ],
  },
  {
    id: 15,
    name: "Salmon, Asparagus & Sweet Potato",
    mealType: "Dinner",
    nutriScoreGrade: "A",
    totalGrams: 760,
    calories: 588,
    protein: 54,
    carbs: 44,
    fat: 22,
    sugar: 6,
    ingredients: [
      { name: "Salmon Fillet", grams: 350 },
      { name: "Asparagus", grams: 200 },
      { name: "Sweet Potato", grams: 210 },
    ],
  },
  {
    id: 16,
    name: "Beef & Vegetable Stir-Fry",
    mealType: "Dinner",
    nutriScoreGrade: "B",
    totalGrams: 740,
    calories: 564,
    protein: 62,
    carbs: 28,
    fat: 22,
    sugar: 7,
    ingredients: [
      { name: "Lean Beef Mince (5% fat)", grams: 400 },
      { name: "Broccoli", grams: 200 },
      { name: "Spinach", grams: 130 },
      { name: "Olive Oil", grams: 10 },
    ],
  },
  {
    id: 17,
    name: "Cottage Cheese & Fruit Bowl",
    mealType: "Snack",
    nutriScoreGrade: "A",
    totalGrams: 380,
    calories: 268,
    protein: 30,
    carbs: 24,
    fat: 6,
    sugar: 16,
    ingredients: [
      { name: "Cottage Cheese", grams: 250 },
      { name: "Blueberries", grams: 100 },
      { name: "Honey", grams: 20 },
    ],
  },
  {
    id: 18,
    name: "Shrimp & Cauliflower Rice",
    mealType: "Dinner",
    nutriScoreGrade: "A",
    totalGrams: 640,
    calories: 312,
    protein: 46,
    carbs: 18,
    fat: 8,
    sugar: 5,
    ingredients: [
      { name: "Shrimp", grams: 350 },
      { name: "Cauliflower", grams: 250 },
      { name: "Olive Oil", grams: 10 },
    ],
  },
  {
    id: 19,
    name: "Turkey, Kale & Sweet Potato Hash",
    mealType: "Breakfast",
    nutriScoreGrade: "B",
    totalGrams: 700,
    calories: 522,
    protein: 52,
    carbs: 46,
    fat: 16,
    sugar: 8,
    ingredients: [
      { name: "Turkey Breast Mince", grams: 350 },
      { name: "Sweet Potato", grams: 250 },
      { name: "Kale", grams: 90 },
    ],
  },
  {
    id: 20,
    name: "Black Bean & Avocado Bowl",
    mealType: "Lunch",
    nutriScoreGrade: "B",
    totalGrams: 620,
    calories: 410,
    protein: 28,
    carbs: 52,
    fat: 16,
    sugar: 5,
    ingredients: [
      { name: "Black Beans (cooked)", grams: 300 },
      { name: "Avocado", grams: 120 },
      { name: "White Rice (cooked)", grams: 150 },
      { name: "Lime", grams: 30 },
    ],
  },
  {
    id: 21,
    name: "Chicken, Brussels Sprouts & Quinoa",
    mealType: "Dinner",
    nutriScoreGrade: "A",
    totalGrams: 820,
    calories: 642,
    protein: 68,
    carbs: 54,
    fat: 16,
    sugar: 5,
    ingredients: [
      { name: "Chicken Breast (raw)", grams: 400 },
      { name: "Brussels Sprouts", grams: 220 },
      { name: "Quinoa (cooked)", grams: 200 },
    ],
  },
]

export function getRecipeById(id: number): Recipe | undefined {
  return RECIPES.find((r) => r.id === id)
}
